apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt-secret: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  user: "guest"
  password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
type: Opaque
stringData:
  user: "admin"
  password: "admin"
